#!/bin/bash

name=(BaconRanger ChromeNinja darkmastermindz Foxtrek_64 HGMPlays Intellihack Lieutenant\ Nakuu Matt\ \|\ WizardCM greenbigfrog nubbyninja Nighthawk Gizoogle Banana\ Nut\ Muffins)
body=(Screenshare\ when discord.gg/jHkHG @AndyG\#5071\ help\ I\ am\ having\ an\ issue Please\ stay\ on\ topic. If\ anyone\ wants\ to\ join\ my\ development\ team,\ DM\ me aaaaaaaaaaaaaaaa How\ do\ I\ use\ a\ selfbot? hi)
function generate () {
echo ${name[$(shuf -i 0-10 -n 1)]} at $(date "+%I:%M %p")
echo ${body[$(shuf -i 0-7 -n 1)]}
printf '\n' * '\n'
}
printf "How many lines would you like to generate? > "
read incr
printf '\n' * '\n'
for ((i=1; i<=incr; i++))
do
generate
if [ "$i" -eq "$incr" ]
then break 2
else sleep $(shuf -i 1-3 -n 1)
fi
done
